/**
 * Agent Factory
 * Uses LLM to generate new agents with iterative validation and error correction.
 * 
 * Features:
 * - Generate agents from natural language descriptions
 * - Automatic TypeScript validation using Bun
 * - Iterative error correction (feeds errors back to LLM)
 * - Saves valid agents to the agents/ directory
 * 
 * Commands:
 * - !help - Show available commands
 * - !create <name> <description> - Create a new agent
 * - !create-with-prompt <name> - Interactive agent creation with custom prompts
 * - !validate <code> - Validate agent code without saving
 * - !list - List generated agents
 * - !show <name> - Show agent source code
 * - !edit <name> <instructions> - Edit an existing agent
 * - !delete <name> - Delete a generated agent
 */

import type { AgentDefinition, AgentSessionContext, LLMParams } from '../lib/agent.js';
import type { Chunk } from '../lib/chunk.js';
import { createTextChunk, createNullChunk } from '../lib/chunk.js';
import { filter, map, mergeMap, catchError, EMPTY } from '../lib/stream.js';
import { mkdirSync, existsSync, readdirSync, readFileSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const AGENTS_DIR = join(__dirname, '..', 'agents');

const MAX_RETRIES = 3;

const HELP_MESSAGE = `🤖 **Agent Factory**

Create new ObservableCAFE agents using natural language descriptions!

**Commands:**
- \`!help\` - Show this help message
- \`!create <name> <description>\` - Create a new agent from description
- \`!create-with-prompt <name>\` - Interactive creation with custom system prompt
- \`!validate <typescript code>\` - Validate code without saving
- \`!list\` - List all generated agents
- \`!show <name>\` - Display agent source code
- \`!edit <name> <instructions>\` - Edit an existing agent
- \`!delete <name>\` - Delete a generated agent
- \`!visualize <name>\` - Visualize agent pipeline using RxMarbles-style diagram

**Example:**
\`!create weather-agent An agent that fetches weather data from the open-meteo.com api (example URL: https://api.open-meteo.com/v1/forecast?latitude=59.3345&longitude=18.0632&current_weather=true)\`

The agent will:
1. Generate TypeScript code from your description
2. Validate the code using Bun's TypeScript compiler
3. If errors are found, automatically retry with fixes
4. Save the final valid agent to \`agents/<name>.ts\``;

const AGENT_TEMPLATE = `/**
 * {{DESCRIPTION}}
 *
 * Generated by Agent Factory
 */

import type { AgentDefinition, AgentSessionContext } from '../lib/agent.js';
import type { Chunk } from '../lib/chunk.js';
import { createTextChunk } from '../lib/chunk.js';
import { filter, map, mergeMap, catchError, EMPTY } from '../lib/stream.js';

export const {{AGENT_NAME}}: AgentDefinition = {
  name: '{{AGENT_NAME}}',
  description: '{{DESCRIPTION}}',
  allowsReload: true,  // Set to false to prevent agent reloads (for stateful agents)
  persistsState: true,  // Set to false to disable auto-persistence
  configSchema: {
    type: 'object',
    properties: {},
    required: []
  },

  initialize(session: AgentSessionContext) {
    const sub = session.inputStream.pipe(
      filter((c: Chunk) => c.contentType === 'text'),
      map((c: Chunk) => {
        if (c.annotations['chat.role']) return c;
        return { ...c, annotations: { ...c.annotations, 'chat.role': 'user' } };
      }),
      filter((c: Chunk) => {
        const trustLevel = c.annotations['security.trust-level'];
        return !trustLevel || trustLevel.trusted !== false;
      }),
      mergeMap(async (chunk: Chunk) => {
        // Agent implementation goes here
        // IMPORTANT: Call session.callbacks?.onFinish() when done generating response
{{IMPLEMENTATION}}
      }),
      catchError((err: Error) => { session.errorStream.next(err); return EMPTY; })
    ).subscribe({
      next: (c: Chunk) => {
        session.outputStream.next(c);
      }
    });

    session.pipelineSubscription = sub;
  }
};

export default {{AGENT_NAME}};`;

const SYSTEM_PROMPT_GENERATE = `You are an expert TypeScript developer specializing in ObservableCAFE agent development.

CRITICAL: Output ONLY valid TypeScript code. No markdown, no explanations, no prose.

## Agent Architecture

Agents are pipeline builders that receive inputStream and build RxJS pipelines that emit to outputStream.

Key concepts:
1. **inputStream** - Subject<Chunk> that receives incoming messages
2. **outputStream** - Subject<Chunk> where responses are emitted  
3. **errorStream** - Subject<Error> for error handling
4. **session.schedule(cron, callback)** - For background agents to schedule tasks
5. **session.createLLMChunkEvaluator()** - Creates an LLM evaluator

## Required Code Structure

\`\`\`typescript
import type { AgentDefinition, AgentSessionContext } from '../lib/agent.js';
import type { Chunk } from '../lib/chunk.js';
import { createTextChunk, createNullChunk } from '../lib/chunk.js';
import { filter, map, mergeMap, catchError, EMPTY } from '../lib/stream.js';

export const myAgent: AgentDefinition = {
  name: 'my-agent',
  description: 'What this agent does',
  allowsReload: true,  // Set to false to prevent agent reloads (for stateful agents)
  persistsState: true,  // Set to false to disable auto-persistence
  configSchema: {
    type: 'object',
    properties: {},
    required: []
  },

  initialize(session: AgentSessionContext) {
    const sub = session.inputStream.pipe(
      filter((c: Chunk) => c.contentType === 'text'),
      map((c: Chunk) => {
        if (c.annotations['chat.role']) return c;
        return { ...c, annotations: { ...c.annotations, 'chat.role': 'user' } };
      }),
      filter((c: Chunk) => {
        const trustLevel = c.annotations['security.trust-level'];
        return !trustLevel || trustLevel.trusted !== false;
      }),
      mergeMap(async (chunk: Chunk) => {
        // Your agent logic here
        const response = createTextChunk('Hello!', 'my-agent', { 'chat.role': 'assistant', 'parsers.markdown.enabled': true });
        // IMPORTANT: Call session.callbacks?.onFinish() when done generating response
        if (session.callbacks?.onFinish) {
          session.callbacks.onFinish();
        }
        return response;
      }),
      catchError((err: Error) => { session.errorStream.next(err); return EMPTY; })
    ).subscribe({
      next: (c: Chunk) => {
        session.outputStream.next(c);
      }
    });

    session.pipelineSubscription = sub;
  }
};

export default myAgent;
\`\`\`

## Output Rules

1. Start with imports
2. Define the AgentDefinition object with name, description, configSchema, initialize
3. End with export default
4. NO markdown code blocks (no triple backticks)
5. NO explanatory text before or after the code
6. NO "Here's the code" or similar phrases
7. Code must be complete and valid TypeScript`

const SYSTEM_PROMPT_FIX = `You are an expert TypeScript developer. Fix the provided ObservableCAFE agent code based on the compilation errors.

## Rules:
1. Fix ALL TypeScript errors shown
2. Keep the original functionality intact
3. Ensure all imports are correct
4. Make sure the agent follows the standard ObservableCAFE agent pattern

## Common Fixes:
- Missing imports (add them)
- Type errors (fix types or add type assertions)
- Syntax errors (fix brackets, semicolons)
- Undefined variables (define or import them)
- Incorrect property access (fix property names)

## Output Format

Respond with ONLY the corrected TypeScript code. No markdown, no explanations.`;

interface ValidationResult {
  valid: boolean;
  errors: string[];
}

async function validateAgentCode(code: string): Promise<ValidationResult> {
  const errors: string[] = [];
  
  try {
    // Use Bun's transpiler to check for syntax/type errors
    const transpiler = new Bun.Transpiler({
      loader: 'ts',
      target: 'bun',
    });
    
    // Try to transpile the code - this catches syntax errors
    const result = transpiler.transformSync(code);
    
    // Additional checks for common agent issues
    if (!code.includes('export const') && !code.includes('export default')) {
      errors.push('Missing export statement. Agent must export a const or default export.');
    }
    
    if (!code.includes('AgentDefinition')) {
      errors.push('Missing AgentDefinition type import or usage.');
    }
    
    if (!code.includes('initialize')) {
      errors.push('Missing initialize method in agent definition.');
    }
    
    if (!code.includes('inputStream')) {
      errors.push('Agent should use inputStream for receiving messages.');
    }
    
    if (!code.includes('outputStream')) {
      errors.push('Agent should use outputStream for sending responses.');
    }
    
    return { valid: errors.length === 0, errors };
  } catch (err: any) {
    // Transpilation error - syntax/type issue
    const errorMessage = err.message || String(err);
    errors.push(errorMessage);
    return { valid: false, errors };
  }
}

/**
 * Extract the largest TypeScript code block from LLM output.
 * Handles cases where LLM includes prose, multiple code blocks, or markdown.
 */
function extractLargestCodeBlock(text: string): string {
  // Pattern to match code blocks: ```typescript...``` or ```ts...``` or ```...```
  const codeBlockPattern = /```(?:typescript|ts)?\n?([\s\S]*?)```/g;
  const matches: string[] = [];
  
  let match;
  while ((match = codeBlockPattern.exec(text)) !== null) {
    matches.push(match[1].trim());
  }
  
  if (matches.length > 0) {
    // Return the largest code block (most likely to be the full agent)
    return matches.reduce((a, b) => a.length > b.length ? a : b);
  }
  
  // No code blocks found - try to extract code by looking for common patterns
  // Look for content between imports and the last export
  const importMatch = text.match(/^(import\s+.*?from\s+['"].*?['"];?\s*)+/);
  const exportMatch = text.match(/export\s+(?:const|default)\s+\w+.*?;/);
  
  if (importMatch || exportMatch) {
    const startIdx = importMatch ? text.indexOf(importMatch[0]) : 0;
    const endIdx = exportMatch 
      ? text.indexOf(exportMatch[0]) + exportMatch[0].length 
      : text.length;
    return text.slice(startIdx, endIdx).trim();
  }
  
  // Last resort: return the original text stripped of obvious prose markers
  return text
    .replace(/^(Here is|Here's|The following|This is|Below is)[^\n]*/i, '')
    .replace(/\n\n(Note:|Explanation:|This code|This agent)[^]*/i, '')
    .trim();
}

/**
 * Analyze agent code to extract pipeline information for visualization
 */
function analyzeAgentPipeline(code: string): any {
  const pipeline: any = {
    name: 'Unknown Pipeline',
    description: '',
    operators: [],
    sourceCode: code
  };
  
  // Extract agent name from export statement
  const nameMatch = code.match(/export\s+const\s+(\w+):\s*AgentDefinition/);
  if (nameMatch) {
    pipeline.name = nameMatch[1];
  }
  
  // Extract description from JSDoc or agent definition
  const descMatch = code.match(/description:\s*['"]([^'"]+)['"]/);
  if (descMatch) {
    pipeline.description = descMatch[1];
  }
  
  // Parse the pipe chain to extract meaningful operations
  const pipeMatch = code.match(/\.pipe\(([\s\S]*?)\)\s*\.subscribe/);
  if (pipeMatch) {
    const pipeContent = pipeMatch[1];
    const operators = parsePipeContent(pipeContent);
    pipeline.operators = operators;
  }
  
  return pipeline;
}

/**
 * Parse pipe content to extract meaningful operations
 */
function parsePipeContent(content: string): any[] {
  const operators = [];
  
  // Split by top-level commas (not inside parentheses)
  const parts = splitPipeParts(content);
  
  for (const part of parts) {
    const op = parseOperator(part.trim());
    if (op) {
      operators.push(op);
    }
  }
  
  return operators;
}

/**
 * Split pipe content by top-level commas
 */
function splitPipeParts(content: string): string[] {
  const parts = [];
  let depth = 0;
  let current = '';
  
  for (const char of content) {
    if (char === '(' || char === '[' || char === '{') {
      depth++;
    } else if (char === ')' || char === ']' || char === '}') {
      depth--;
    } else if (char === ',' && depth === 0) {
      parts.push(current);
      current = '';
      continue;
    }
    current += char;
  }
  
  if (current.trim()) {
    parts.push(current);
  }
  
  return parts;
}

/**
 * Parse a single operator call
 */
function parseOperator(part: string): any | null {
  part = part.trim();
  
  // Skip subscribe and other terminal operations
  if (part.startsWith('subscribe') || part.startsWith('catchError')) {
    return null;
  }
  
  // Extract function calls like filter(...), map(...), mergeMap(...)
  const funcMatch = part.match(/^(\w+)\s*\((.*)\)$/s);
  if (!funcMatch) {
    // Check for custom evaluators passed directly
    if (part.match(/^[a-zA-Z_][a-zA-Z0-9_]*$/)) {
      return {
        name: part,
        type: 'Custom Evaluator',
        description: getEvaluatorDescription(part)
      };
    }
    return null;
  }
  
  const [, funcName, args] = funcMatch;
  
  // Parse based on operator type
  switch (funcName) {
    case 'filter':
      return parseFilter(args);
    case 'map':
      return parseMap(args);
    case 'mergeMap':
    case 'switchMap':
    case 'concatMap':
      return parseMapOperator(funcName, args);
    case 'tap':
      return parseTap(args);
    case 'debounceTime':
    case 'throttleTime':
      return {
        name: funcName,
        type: 'Timing Control',
        description: `Waits ${args}ms before processing`
      };
    case 'distinctUntilChanged':
      return {
        name: funcName,
        type: 'Deduplication',
        description: 'Ignores consecutive duplicate values'
      };
    default:
      // Check if it's a custom evaluator function
      if (args === '' || args === 'session') {
        return {
          name: funcName,
          type: 'Custom Evaluator',
          description: getEvaluatorDescription(funcName)
        };
      }
      return {
        name: funcName,
        type: 'RxJS Operator',
        description: getOperatorDescription(funcName)
      };
  }
}

/**
 * Parse filter operator to extract condition
 */
function parseFilter(args: string): any {
  // Clean up the arguments
  const cleanArgs = args.replace(/\s+/g, ' ').trim();
  
  // Extract condition from arrow function
  const arrowMatch = cleanArgs.match(/\([^)]*\)\s*=>\s*(.+)/);
  if (arrowMatch) {
    const condition = arrowMatch[1].trim();
    
    // Parse common filter patterns
    if (condition.includes('contentType')) {
      const typeMatch = condition.match(/contentType\s*===?\s*['"]([^'"]+)['"]/);
      if (typeMatch) {
        return {
          name: 'filter',
          type: 'Type Filter',
          description: `Only ${typeMatch[1]} content`
        };
      }
    }
    
    if (condition.includes('trust')) {
      return {
        name: 'filter',
        type: 'Security Filter',
        description: 'Trusted content only'
      };
    }
    
    if (condition.includes('chat.role')) {
      const roleMatch = condition.match(/chat\.role\s*===?\s*['"]([^'"]+)['"]/);
      if (roleMatch) {
        return {
          name: 'filter',
          type: 'Role Filter',
          description: `Only ${roleMatch[1]} messages`
        };
      }
    }
    
    // Generic filter
    return {
      name: 'filter',
      type: 'Condition Filter',
      description: condition.length > 40 ? condition.slice(0, 40) + '...' : condition
    };
  }
  
  return {
    name: 'filter',
    type: 'RxJS Operator',
    description: 'Filters based on condition'
  };
}

/**
 * Parse map operator to extract transformation
 */
function parseMap(args: string): any {
  const cleanArgs = args.replace(/\s+/g, ' ').trim();
  
  // Extract transformation from arrow function
  const arrowMatch = cleanArgs.match(/\([^)]*\)\s*=>\s*(.+)/);
  if (arrowMatch) {
    const transform = arrowMatch[1].trim();
    
    // Parse common map patterns
    if (transform.includes('annotateChunk')) {
      const annotMatch = transform.match(/annotateChunk\([^,]+,\s*['"]([^'"]+)['"]/);
      if (annotMatch) {
        return {
          name: 'map',
          type: 'Annotation',
          description: `Sets ${annotMatch[1]}`
        };
      }
    }
    
    if (transform.includes('return')) {
      const returnVal = transform.match(/return\s+(.+?);?$/);
      if (returnVal) {
        return {
          name: 'map',
          type: 'Transform',
          description: returnVal[1].length > 40 ? returnVal[1].slice(0, 40) + '...' : returnVal[1]
        };
      }
    }
    
    return {
      name: 'map',
      type: 'Transform',
      description: transform.length > 40 ? transform.slice(0, 40) + '...' : transform
    };
  }
  
  return {
    name: 'map',
    type: 'RxJS Operator',
    description: 'Transforms values'
  };
}

/**
 * Parse mergeMap/switchMap operators
 */
function parseMapOperator(funcName: string, args: string): any {
  const cleanArgs = args.replace(/\s+/g, ' ').trim();
  
  // Check for completeTurnWithLLM
  if (cleanArgs.includes('completeTurnWithLLM')) {
    return {
      name: funcName,
      type: 'LLM Call',
      description: 'Generates LLM response'
    };
  }
  
  // Check for evaluator calls
  const evaluatorMatch = cleanArgs.match(/(create\w+Evaluator|processWithEvaluator|\w+Evaluator)/);
  if (evaluatorMatch) {
    return {
      name: funcName,
      type: 'Async Processing',
      description: getEvaluatorDescription(evaluatorMatch[1])
    };
  }
  
  // Check for session calls
  if (cleanArgs.includes('session.')) {
    const sessionMatch = cleanArgs.match(/session\.(\w+)/);
    if (sessionMatch) {
      return {
        name: funcName,
        type: 'Session Operation',
        description: `Uses ${sessionMatch[1]}`
      };
    }
  }
  
  return {
    name: funcName,
    type: 'Async Transform',
    description: 'Maps to async operation'
  };
}

/**
 * Parse tap operator (side effects)
 */
function parseTap(args: string): any {
  const cleanArgs = args.replace(/\s+/g, ' ').trim();
  
  if (cleanArgs.includes('outputStream')) {
    return {
      name: 'tap',
      type: 'Side Effect',
      description: 'Outputs to stream'
    };
  }
  
  if (cleanArgs.includes('errorStream')) {
    return {
      name: 'tap',
      type: 'Error Handling',
      description: 'Logs errors'
    };
  }
  
  return {
    name: 'tap',
      type: 'Side Effect',
      description: 'Performs side effect'
  };
}

/**
 * Get description for evaluator functions
 */
function getEvaluatorDescription(name: string): string {
  const descriptions: Record<string, string> = {
    parseMarkdownForVoice: 'Parses markdown for voice output',
    generateVoice: 'Generates voice audio',
    analyzeSentiment: 'Analyzes sentiment',
    detectTools: 'Detects tool calls',
    executeTools: 'Executes tools',
    createEvaluator: 'Creates LLM evaluator',
    createLLMChunkEvaluator: 'LLM completion',
    completeTurnWithLLM: 'LLM response generation',
    processWithEvaluator: 'Processes with evaluator'
  };
  
  // Check for partial matches
  for (const [key, desc] of Object.entries(descriptions)) {
    if (name.toLowerCase().includes(key.toLowerCase())) {
      return desc;
    }
  }
  
  return name;
}

/**
 * Get descriptions for common RxJS operators
 */
function getOperatorDescription(op: string): string {
  const descriptions: Record<string, string> = {
    filter: 'Filters chunks based on condition',
    map: 'Transforms chunks',
    mergeMap: 'Maps to observables, then flattens',
    catchError: 'Handles errors',
    debounceTime: 'Debounces chunks',
    distinctUntilChanged: 'Filters duplicates',
    tap: 'Performs side effects',
    switchMap: 'Maps to observable, switching to new'
  };
  
  return descriptions[op] || 'RxJS Operator';
}

async function generateAgentCode(
  evaluator: any,
  name: string,
  description: string,
  systemPrompt: string,
  previousCode?: string,
  previousErrors?: string[]
): Promise<{ code: string; success: boolean; errors: string[] }> {
  let prompt: string;
  
  if (previousCode && previousErrors) {
    // Retry with error feedback
    prompt = `Fix the following agent code that has compilation errors.

Agent Name: ${name}
Description: ${description}

PREVIOUS CODE:
${previousCode}

COMPILATION ERRORS:
${previousErrors.join('\n')}

Provide the corrected TypeScript code only. Output just the code, no explanations.`;
  } else {
    // Initial generation
    prompt = `Create an ObservableCAFE agent named "${name}".

Description: ${description}

Generate the complete TypeScript implementation. Output ONLY valid TypeScript code that can be saved directly to a .ts file.

Requirements:
- Start with imports
- Define the AgentDefinition object
- Include the initialize() method
- End with export default
- NO explanations, NO markdown, NO prose before or after the code`;
  }

  // Combine system prompt with user prompt (since we can't set system prompt on evaluator)
  const fullPrompt = `${systemPrompt}\n\n--- USER REQUEST ---\n\n${prompt}`;
  
  const tempChunk = createTextChunk(fullPrompt, 'agent-factory', {
    'llm.full-prompt': true,
    'chat.role': 'user'
  });

  let rawOutput = '';
  
  try {
    for await (const tokenChunk of evaluator.evaluateChunk(tempChunk)) {
      if (tokenChunk.contentType === 'text') {
        rawOutput += tokenChunk.content as string;
      }
    }
  } catch (err: any) {
    return { code: '', success: false, errors: [`Generation error: ${err.message}`] };
  }

  // Extract the largest code block from the LLM output
  let generatedCode = extractLargestCodeBlock(rawOutput);

  // If the code doesn't have proper agent structure, wrap it
  if (!generatedCode.includes('AgentDefinition')) {
    // The LLM only provided the initialize body, wrap it
    const implementation = generatedCode.includes('initialize(session:')
      ? generatedCode.match(/initialize\(session:[^}]+\{([^]*)\}\s*}/s)?.[1] || generatedCode
      : generatedCode;
    
    const wrappedCode = AGENT_TEMPLATE
      .replace(/\{\{AGENT_NAME\}\}/g, name)
      .replace(/\{\{DESCRIPTION\}\}/g, description)
      .replace('{{IMPLEMENTATION}}', implementation.split('\n').map(l => '    ' + l).join('\n'));
    
    generatedCode = wrappedCode;
  }

  // Validate the code
  const validation = await validateAgentCode(generatedCode);
  
  return {
    code: generatedCode,
    success: validation.valid,
    errors: validation.errors
  };
}

async function generateWithRetry(
  session: AgentSessionContext,
  name: string,
  description: string,
  systemPrompt: string
): Promise<{ code: string; success: boolean; attempts: number; finalErrors: string[] }> {
  let code = '';
  let errors: string[] = [];
  
  const evaluator = session.createLLMChunkEvaluator({ temperature: 0.2, maxTokens: 4000 });
  
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    const result = await generateAgentCode(
      evaluator,
      name,
      description,
      systemPrompt,
      attempt > 1 ? code : undefined,
      attempt > 1 ? errors : undefined
    );
    
    code = result.code;
    errors = result.errors;
    
    if (result.success) {
      return { code, success: true, attempts: attempt, finalErrors: [] };
    }
    
    if (attempt === MAX_RETRIES) {
      return { code, success: false, attempts: attempt, finalErrors: errors };
    }
  }
  
  return { code, success: false, attempts: MAX_RETRIES, finalErrors: errors };
}

function sanitizeAgentName(name: string): string {
  // Convert to valid TypeScript identifier
  return name
    .replace(/[^a-zA-Z0-9_-]/g, '-')
    .replace(/^[^a-zA-Z]/, 'agent-')
    .toLowerCase();
}

function saveAgentFile(name: string, code: string): string {
  const sanitizedName = sanitizeAgentName(name);
  const filePath = join(AGENTS_DIR, `${sanitizedName}.ts`);
  
  // Ensure directory exists
  if (!existsSync(AGENTS_DIR)) {
    mkdirSync(AGENTS_DIR, { recursive: true });
  }
  
  // Write file
  const file = Bun.file(filePath);
  Bun.write(file, code);
  
  return filePath;
}

function listGeneratedAgents(): string[] {
  if (!existsSync(AGENTS_DIR)) {
    return [];
  }
  
  return readdirSync(AGENTS_DIR)
    .filter(f => f.endsWith('.ts'))
    .map(f => f.replace('.ts', ''));
}

function readAgentFile(name: string): string | null {
  const filePath = join(AGENTS_DIR, `${sanitizeAgentName(name)}.ts`);
  if (!existsSync(filePath)) {
    return null;
  }
  return readFileSync(filePath, 'utf-8');
}

function deleteAgentFile(name: string): boolean {
  const filePath = join(AGENTS_DIR, `${sanitizeAgentName(name)}.ts`);
  if (!existsSync(filePath)) {
    return false;
  }
  unlinkSync(filePath);
  return true;
}

export const agentFactory: AgentDefinition = {
  name: 'agent-factory',
  description: 'Creates new agents using LLM with automatic validation and error correction',
  configSchema: {
    type: 'object',
    properties: {
      backend: { type: 'string', description: 'LLM backend (kobold or ollama)' },
      model: { type: 'string', description: 'Model name' },
      systemPrompt: { type: 'string', description: 'System prompt' },
      llmParams: {
        type: 'object',
        properties: {
          temperature: { type: 'number' },
          maxTokens: { type: 'number' },
          topP: { type: 'number' },
          topK: { type: 'number' },
          repeatPenalty: { type: 'number' },
          stop: { type: 'array', items: { type: 'string' } },
          seed: { type: 'number' },
          maxContextLength: { type: 'number' },
          numCtx: { type: 'number' },
        }
      }
    },
    required: []
  },
  
  async initialize(session: AgentSessionContext) {
    // Send help message on initialization
    session.outputStream.next(createTextChunk(
      HELP_MESSAGE,
      'agent-factory',
      { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
    ));
    
    session.inputStream.pipe(
      filter((chunk: Chunk) => chunk.contentType === 'text'),
      map((chunk: Chunk) => {
        if (chunk.annotations['chat.role']) return chunk;
        return { ...chunk, annotations: { ...chunk.annotations, 'chat.role': 'user' } };
      }),
      filter((chunk: Chunk) => {
        const trustLevel = chunk.annotations['security.trust-level'];
        return !trustLevel || trustLevel.trusted !== false;
      }),
      mergeMap(async (chunk: Chunk) => {
        const text = (chunk.content as string).trim();
        
        if (text === '!help') {
          return createTextChunk(HELP_MESSAGE, 'agent-factory', { 'chat.role': 'assistant', 'parsers.markdown.enabled': true });
        }
        
        if (text.startsWith('!create ')) {
          const args = text.slice(8).trim();
          const spaceIdx = args.indexOf(' ');
          
          if (spaceIdx < 0) {
            return createTextChunk(
              'Usage: `!create <name> <description>`\n\nExample: `!create weather-agent An agent that fetches weather data from the open-meteo.com api (e.g. https://api.open-meteo.com/v1/forecast?latitude=59.3345&longitude=18.0632&current_weather=true)`',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const name = args.slice(0, spaceIdx).trim();
          const description = args.slice(spaceIdx + 1).trim();
          
          if (!name || !description) {
            return createTextChunk(
              'Please provide both a name and description for the agent.',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          // Send progress message
          session.outputStream.next(createTextChunk(
            `🔄 Creating agent "${name}"...\nDescription: ${description}\n\nGenerating code...`,
            'agent-factory',
            { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
          ));
          
          // Generate with retry
          const result = await generateWithRetry(session, name, description, SYSTEM_PROMPT_GENERATE);
          
          if (result.success) {
            // Save the file
            const filePath = saveAgentFile(name, result.code);
            
            return createTextChunk(
              `✅ Agent "${name}" created successfully!\n\n📄 Saved to: ${filePath}\n📝 Attempts: ${result.attempts}\n\nThe agent has been saved and will be available after server restart (or use \`!reload\` if implemented).\n\nTo use the new agent, restart the server or create a new session with agent ID: "${sanitizeAgentName(name)}"`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          } else {
            // Show the code and errors (full code, not truncated)
            const errorMessage = result.finalErrors.join('\n- ');
            
            return createTextChunk(
              `❌ Failed to create agent "${name}" after ${result.attempts} attempts.\n\n**Errors:**\n- ${errorMessage}\n\n**Last Generated Code:**\n\`\`\`typescript\n${result.code}\n\`\`\`\n\nYou can try:\n1. Providing a clearer description\n2. Breaking down the functionality into simpler steps\n3. Using \`!validate\` to test code snippets first`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
        }
        
        if (text.startsWith('!create-with-prompt ')) {
          const name = text.slice(20).trim();
          
          if (!name) {
            return createTextChunk(
              'Usage: `!create-with-prompt <name>`\n\nThen provide the system prompt in your next message.',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          return createTextChunk(
            `Creating agent "${name}" with custom prompt.\n\nPlease provide the system prompt that describes how this agent should behave:`,
            'agent-factory',
            { 'chat.role': 'assistant', 'pipeline.creation.pending': name }
          );
        }
        
        if (text.startsWith('!validate ')) {
          const code = text.slice(10).trim();
          
          if (!code) {
            return createTextChunk(
              'Usage: `!validate <typescript code>`',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const validation = await validateAgentCode(code);
          
          if (validation.valid) {
            return createTextChunk(
              '✅ Code is valid!',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          } else {
            return createTextChunk(
              `❌ Validation errors:\n- ${validation.errors.join('\n- ')}`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
        }
        
        if (text === '!list') {
          const agents = listGeneratedAgents();
          
          if (agents.length === 0) {
            return createTextChunk(
              'No generated agents found in the agents/ directory.',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const agentList = agents.map(a => `- ${a}`).join('\n');
          return createTextChunk(
            `**Generated Agents:**\n\n${agentList}\n\nUse \`!show <name>\` to view source code.`,
            'agent-factory',
            { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
          );
        }
        
        if (text.startsWith('!show ')) {
          const name = text.slice(6).trim();
          const code = readAgentFile(name);
          
          if (code === null) {
            return createTextChunk(
              `Agent "${name}" not found. Use \`!list\` to see available agents.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const truncatedCode = code.length > 2000 
            ? code.slice(0, 2000) + '\n\n... (code truncated, total length: ' + code.length + ' chars)'
            : code;
          
          return createTextChunk(
            `**Agent: ${name}**\n\n\`\`\`typescript\n${truncatedCode}\n\`\`\``,
            'agent-factory',
            { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
          );
        }
        
        if (text.startsWith('!edit ')) {
          const args = text.slice(6).trim();
          const spaceIdx = args.indexOf(' ');
          
          if (spaceIdx < 0) {
            return createTextChunk(
              'Usage: `!edit <name> <instructions>`\n\nExample: `!edit weather-agent Add error handling for API failures`',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const name = args.slice(0, spaceIdx).trim();
          const instructions = args.slice(spaceIdx + 1).trim();
          
          const existingCode = readAgentFile(name);
          if (existingCode === null) {
            return createTextChunk(
              `Agent "${name}" not found. Use \`!list\` to see available agents.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          session.outputStream.next(createTextChunk(
            `🔄 Editing agent "${name}"...\nInstructions: ${instructions}`,
            'agent-factory',
            { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
          ));
          
          const editPrompt = `Edit the following ObservableCAFE agent according to these instructions:

INSTRUCTIONS: ${instructions}

CURRENT CODE:
${existingCode}

Provide the complete updated TypeScript code.`;
          
  const evaluator = session.createLLMChunkEvaluator({ temperature: 0.2, maxTokens: 4000 });
          const tempChunk = createTextChunk(editPrompt, 'agent-factory', {
            'llm.full-prompt': true,
            'chat.role': 'user'
          });
          
          let editedCode = '';
          try {
            for await (const tokenChunk of evaluator.evaluateChunk(tempChunk)) {
              if (tokenChunk.contentType === 'text') {
                editedCode += tokenChunk.content as string;
              }
            }
          } catch (err: any) {
            return createTextChunk(
              `❌ Error during edit: ${err.message}`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          // Clean up and validate
          editedCode = editedCode.trim().replace(/^```typescript\n?/i, '').replace(/^```ts\n?/i, '').replace(/```\s*$/i, '').trim();
          const validation = await validateAgentCode(editedCode);
          
          if (validation.valid) {
            const filePath = saveAgentFile(name, editedCode);
            return createTextChunk(
              `✅ Agent "${name}" updated successfully!\n\n📄 Saved to: ${filePath}`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          } else {
            return createTextChunk(
              `❌ Edit produced invalid code:\n- ${validation.errors.join('\n- ')}\n\nOriginal code preserved.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
        }
        
        if (text.startsWith('!delete ')) {
          const name = text.slice(8).trim();
          
          if (!name) {
            return createTextChunk(
              'Usage: `!delete <name>`',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const success = deleteAgentFile(name);
          
          if (success) {
            return createTextChunk(
              `✅ Agent "${name}" deleted.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          } else {
            return createTextChunk(
              `Agent "${name}" not found.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
        }
        
        if (text.startsWith('!visualize ')) {
          const name = text.slice(11).trim();
          
          if (!name) {
            return createTextChunk(
              'Usage: `!visualize <name>`',
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          const code = readAgentFile(name);
          if (code === null) {
            return createTextChunk(
              `Agent "${name}" not found. Use \`!list\` to see available agents.`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
          
          // Analyze the agent code to extract pipeline information
          const pipeline = analyzeAgentPipeline(code);
          
          // Create a visualization chunk with pipeline data
          return createNullChunk(
            'agent-factory',
            { 
              'visualizer.type': 'rx-marbles',
              'visualizer.agent': name,
              'visualizer.pipeline': pipeline,
              'visualizer.code': code
            }
          );
        }
        
        // Check for pending creation with custom prompt
        const lastConfigChunk = [...session.history].reverse().find(c => 
          c.annotations['pipeline.creation.pending']
        );
        
        if (lastConfigChunk && text && !text.startsWith('!')) {
          const pendingName = lastConfigChunk.annotations['pipeline.creation.pending'];
          const customPrompt = text;
          
          session.outputStream.next(createTextChunk(
            `🔄 Creating agent "${pendingName}" with custom prompt...`,
            'agent-factory',
            { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
          ));
          
          const result = await generateWithRetry(session, pendingName, customPrompt, customPrompt);
          
          if (result.success) {
            const filePath = saveAgentFile(pendingName, result.code);
            return createTextChunk(
              `✅ Agent "${pendingName}" created successfully!\n\n📄 Saved to: ${filePath}\n📝 Attempts: ${result.attempts}`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          } else {
            return createTextChunk(
              `❌ Failed to create agent after ${result.attempts} attempts.\n\nErrors:\n- ${result.finalErrors.join('\n- ')}`,
              'agent-factory',
              { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
            );
          }
        }
        
        // Default: unrecognized command
        return createTextChunk(
          `I don't understand that command. Type \`!help\` for available commands.`,
          'agent-factory',
          { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
        );
      }),
      catchError((error: Error) => {
        console.error('[agent-factory] Error:', error);
        session.errorStream.next(error);
        session.outputStream.next(createTextChunk(
          `❌ Error: ${error.message}`,
          'agent-factory',
          { 'chat.role': 'assistant', 'parsers.markdown.enabled': true }
        ));
        return EMPTY;
      })
    ).subscribe({
      next: (chunk: Chunk) => {
        session.outputStream.next(chunk);
        const callbacks = session.callbacks;
        if (callbacks?.onFinish) {
          callbacks.onFinish();
        }
      },
      error: (error: Error) => session.errorStream.next(error)
    });
  }
};

export default agentFactory;
